<?php
/**
 * @file
 * Code for the Kalamuna Widgets feature.
 */

include_once 'kala_widgets.features.inc';

/**
 * Implementation of hook_entity_info_alter()
 */
function kala_widgets_entity_info_alter(&$entity_info) {
  // Fieldable panel pane bundle to support call-to-action
  $entity_info['fieldable_panels_pane']['bundles']['kala_image'] = array(
    'label' => t('Add responsive image'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_image.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/kala-image',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
